version: '3.8'

services:
  radioss-bot:
    image: ghcr.io/dascanard/radioss-discord:stable
    container_name: radioss-discord-bot
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - ENABLE_RECONNECTION=${ENABLE_RECONNECTION:-false}
      - UPTIME_HEARTBEAT_URL=${UPTIME_HEARTBEAT_URL:-}
    volumes:
      - ./botdata:/app/data